# Google Cloud Build configuration
# Automatically builds and deploys to Cloud Run

steps:
  # Build the Docker image
  - name: 'gcr.io/cloud-builders/docker'
    args:
      - 'build'
      - '-t'
      - 'gcr.io/$PROJECT_ID/ai-study-buddy-backend:$COMMIT_SHA'
      - '-t'
      - 'gcr.io/$PROJECT_ID/ai-study-buddy-backend:latest'
      - '-f'
      - 'Dockerfile.cloudrun'
      - '.'

  # Push the image to Container Registry
  - name: 'gcr.io/cloud-builders/docker'
    args:
      - 'push'
      - 'gcr.io/$PROJECT_ID/ai-study-buddy-backend:$COMMIT_SHA'

  - name: 'gcr.io/cloud-builders/docker'
    args:
      - 'push'
      - 'gcr.io/$PROJECT_ID/ai-study-buddy-backend:latest'

  # Deploy to Cloud Run
  - name: 'gcr.io/google.com/cloudsdktool/cloud-sdk'
    entrypoint: gcloud
    args:
      - 'run'
      - 'deploy'
      - 'ai-study-buddy-backend'
      - '--image'
      - 'gcr.io/$PROJECT_ID/ai-study-buddy-backend:$COMMIT_SHA'
      - '--region'
      - '${_REGION}'
      - '--platform'
      - 'managed'
      - '--allow-unauthenticated'
      - '--memory'
      - '2Gi'
      - '--cpu'
      - '2'
      - '--timeout'
      - '300'
      - '--concurrency'
      - '80'
      - '--min-instances'
      - '0'
      - '--max-instances'
      - '10'
      - '--set-env-vars'
      - 'ENVIRONMENT=production'

# Substitutions (can be overridden)
substitutions:
  _REGION: us-central1

# Build options
options:
  logging: CLOUD_LOGGING_ONLY

# Images to store
images:
  - 'gcr.io/$PROJECT_ID/ai-study-buddy-backend:$COMMIT_SHA'
  - 'gcr.io/$PROJECT_ID/ai-study-buddy-backend:latest'

timeout: 1800s
